/* 
 * This file is autogenerated from a raw rgb56 image, the file format has a 16 bits
 * per pixel (RGB565) and is contained in an array of uint16_t as follows:
 *
 * INDEX 	VALUE 	DESCRIPTION		 
 * 00 		0xHHHH  image Height, max height 65535 pixels
 * 01 		0xWWWW 	image width, max width 65535 pixels
 * 02 		0xXXXX 	This represents a single pixel and the first one
 * 03 		0xXXXX 	This represent the second pixel of the image.
 * ...		...		continues pixel data
 * Nth 		0xABCD 	[NOT IMPLEMENTED] padding to detect image tail
 *
 * - C.Alvarado
 */
#ifndef _TMP_TEST_H
#define _TMP_TEST_H

#include <stdint.h>

#define _TMP_TEST_SIZE 40002

extern const uint16_t _tmp_test[_TMP_TEST_SIZE];

#endif /* _TMP_TEST_H */
