/* 
 * This file is autogenerated from a raw rgb56 image, the file format has a 16 bits
 * per pixel (RGB565) and is contained in an array of uint16_t as follows:
 *
 * INDEX 	VALUE 	DESCRIPTION		 
 * 00 		0xHHHH  image Height, max height 65535 pixels
 * 01 		0xWWWW 	image width, max width 65535 pixels
 * 02 		0xXXXX 	This represents a single pixel and the first one
 * 03 		0xXXXX 	This represent the second pixel of the image.
 * ...		...		continues pixel data
 * Nth 		0xABCD 	[NOT IMPLEMENTED] padding to detect image tail
 *
 * - C.Alvarado
 */
#ifndef DISDAIN_INTO_046_0_H
#define DISDAIN_INTO_046_0_H

#include <stdint.h>

#define DISDAIN_INTO_046_0_SIZE 57602

extern const uint16_t disdain_into_046_0[DISDAIN_INTO_046_0_SIZE];

#endif /* DISDAIN_INTO_046_0_H */
