#------------------------------------------------------------------------------
# 
# This makefile has to be appended at the begining of the _makefile_ file 
# generated by Erika, as follows:
# 			include user.mk
# 
# Fri, Feb 9, 2024
# - By Christian Alvarado
#------------------------------------------------------------------------------

# Path to compiler
GNU_ARM_ROOT = $(HOME)/Apps/gcc-arm-none-eabi-9-2019-q4-major

MDEV_DIR:=mdev mdev/inc mdev/src
USER_DIR:=test $(MDEV_DIR)
USER_SRC:=$(foreach dir,$(USER_DIR),$(wildcard $(dir)/*.c))
USER_INC:=$(foreach dir,$(USER_DIR),-I$(dir))

CFLAGS += $(USER_INC) -DLCD_TERM_ENABLED -DSD_POLLING_MODE -g3
APP_SRCS += $(USER_SRC)

#EE_OPT += _MDEV_USE_LEDS_
#EE_OPT += _MDEV_USE_LCD35RT_

# st-flash write c_mX.bin 0x8000000

# --------------------------------------------
#Widget.c Event.c Touch.c STMPE811QTR.c\
physical_interface.c wifi_driver.c

#app.c ui.c json_parser.c ipapi_json.c openweather.c web_app.c\
#OW01d.c OW02d.c OW03d.c OW04d.c OW09d.c OW10d.c OW11d.c OW12d.c OW13d.c OW50d.c\
#zero.c one.c two.c three.c four.c five.c six.c seven.c eight.c nine.c\
#location.c no_location.c \
#WiFi_no.c WiFi_settingup.c WiFi_connected.c\
#settings_on.c settings_off.c
